### ISSUE TITLE
What's the  username/password to Cobbler I can't seem to login to it

### ISSUE THREAD

**Issue by jmakanjuola** [jossy/cobbler-ubuntu#1]
Hey Josef thank you so much for your tutorial. I just have a question what's the username/password to cobbler?

Thanks a lot in advance!

**Comment by jossy** [comment]
@jmakanjuola You should be able to login using the default user and password: cobbler/cobbler

**Comment by jmakanjuola** [comment]
Thanks for the reply when I enter the username/password here is what I get

Error message

[Errno 13] Permission denied: '/var/lib/cobbler/webui_sessions/sessionids5d89f23osdfe87j8wjqw3mkoluk9v9p'
Request Method:	POST
Request URL:	http://192.168.1.48/cobbler_web/do_login
Django Version:	1.6.1
Exception Type:	OSError
Exception Value:	
[Errno 13] Permission denied: '/var/lib/cobbler/webui_sessions/sessionids5d89f23osdfe87j8wjqw3mkoluk9v9p'
Exception Location:	/usr/lib/python2.7/dist-packages/django/contrib/sessions/backends/file.py in save, line 125
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/share/cobbler/web/cobbler_web',
 '/usr/share/cobbler/web',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Server time:	Thu, 7 May 2015 19:08:10 -0700

**Comment by jossy** [comment]
Please keep in mind that this is only a demo repository and not intended to leave you with a production-ready installation.

But: This problem is caused by incorrect permissions of `/var/lib/cobbler/webui_sessions`. You can find the appropriate workaround here:

https://github.com/jossy/cobbler-ubuntu/blob/master/scripts/20_config_cobbler.sh#L25
